baseURL = "https://www.codetea.top/"
title = "OPdbg"
theme = "coder"
languageCode = "en"
defaultContentLanguage = "en" 

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
disqusShortname = "yourdiscussshortname"

[params]
  author = "OrcasCode"
  info = "A Simple Learner in Cyberspace Security and Tea Science"
  description = "OolongCode and OrcasCode's CyberSpace!"
  keywords = "blog,developer,personal"
  avatarurl = "images/orca.jpg"

  favicon_32 = "/favicon-32x32.png"
  favicon_16 = "/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/OolongCode/"


[menu]
  [[menu.main]]
    name = "About"      
    url = "/about/"      
    weight = 1    
  [[menu.main]]     
    url = "/posts/"
    name = "Posts"
    weight = 2 
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
  
  [[menu.main]]
    name = "Tags"
    url  = "/tags/"
    weight = 4

  [[menu.main]]
    name       = "Link"
    url        = "/link/"
    weight = 5

